[package]
name = "ecocode-rust-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ec2 = { path = "../ecocode-rust/rules/ec2" }

[workspace.metadata.dylint]
libraries = [
    { path = "../ecocode-rust/rules/ec2" }
]