version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - default
      - host_network

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar_scanner
    depends_on:
      - sonarqube
    volumes:
      - ./sonar-project.properties:/sonar-project.properties
      - ./src:/usr/src
    entrypoint: |
      /bin/bash -c "
      while ! nc -z sonarqube 9000; do
        sleep 1;
      done;
      sonar-scanner"
    networks:
      - default

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data:

networks:
  host_network:
    external: true
